import { z } from "zod";

export const churchEditSchema = z.object({
  name_en: z.string().min(1, "English name is required"),
  name_am: z.string().min(1, "Amharic name is required"),
  name_or: z.string(),
  name_so: z.string(),
  name_ti: z.string(),
  description_en: z.string().min(1, "English description is required"),
  description_am: z.string().min(1, "Amharic description is required"),
  description_or: z.string(),
  description_so: z.string(),
  description_ti: z.string(),
  category: z.enum(["church", "monastery", "female-monastery"]),
  phone_number: z.string().min(1, "Phone number is required"),
  email: z.string(),
  website: z.string(),
  city_en: z.string(),
  city_am: z.string(),
  city_or: z.string(),
  city_so: z.string(),
  city_ti: z.string(),
  address_en: z.string(),
  address_am: z.string(),
  address_or: z.string(),
  address_so: z.string(),
  address_ti: z.string(),
  country_en: z.string(),
  country_am: z.string(),
  country_or: z.string(),
  country_so: z.string(),
  country_ti: z.string(),
  founded_year: z.string(),
});

export const bankAccountSchema = z.object({
  bank_name_en: z.string().min(1, "English bank name is required"),
  bank_name_am: z.string().min(1, "Amharic bank name is required"),
  bank_name_or: z.string(),
  bank_name_so: z.string(),
  bank_name_ti: z.string(),
  account_number: z.string().min(1, "Account number is required"),
  account_holder_name: z.string().min(1, "Account holder name is required"),
  branch_name: z.string(),
  swift_code: z.string(),
  is_primary: z.boolean(),
});
