/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardUsersIndexRouteImport } from './routes/_authenticated/dashboard/users/index'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/dashboard/settings/index'
import { Route as AuthenticatedDashboardPaymentsIndexRouteImport } from './routes/_authenticated/dashboard/payments/index'
import { Route as AuthenticatedDashboardNotificationsIndexRouteImport } from './routes/_authenticated/dashboard/notifications/index'
import { Route as AuthenticatedDashboardEventsIndexRouteImport } from './routes/_authenticated/dashboard/events/index'
import { Route as AuthenticatedDashboardDonationsIndexRouteImport } from './routes/_authenticated/dashboard/donations/index'
import { Route as AuthenticatedDashboardContentIndexRouteImport } from './routes/_authenticated/dashboard/content/index'
import { Route as AuthenticatedDashboardChurchesIndexRouteImport } from './routes/_authenticated/dashboard/churches/index'
import { Route as AuthenticatedDashboardCategoriesIndexRouteImport } from './routes/_authenticated/dashboard/categories/index'
import { Route as AuthenticatedDashboardCampaignsIndexRouteImport } from './routes/_authenticated/dashboard/campaigns/index'
import { Route as AuthenticatedDashboardBibleIndexRouteImport } from './routes/_authenticated/dashboard/bible/index'
import { Route as AuthenticatedDashboardUsersUserIdIndexRouteImport } from './routes/_authenticated/dashboard/users/$userId/index'
import { Route as AuthenticatedDashboardEventsEventIdIndexRouteImport } from './routes/_authenticated/dashboard/events/$eventId/index'
import { Route as AuthenticatedDashboardContentNewIndexRouteImport } from './routes/_authenticated/dashboard/content/new/index'
import { Route as AuthenticatedDashboardContentContentIdIndexRouteImport } from './routes/_authenticated/dashboard/content/$contentId/index'
import { Route as AuthenticatedDashboardChurchesNewIndexRouteImport } from './routes/_authenticated/dashboard/churches/new/index'
import { Route as AuthenticatedDashboardChurchesChurchIdIndexRouteImport } from './routes/_authenticated/dashboard/churches/$churchId/index'
import { Route as AuthenticatedDashboardBibleBookIdIndexRouteImport } from './routes/_authenticated/dashboard/bible/$bookId/index'
import { Route as AuthenticatedDashboardBibleBookIdChapterIdIndexRouteImport } from './routes/_authenticated/dashboard/bible/$bookId/$chapterId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardUsersIndexRoute =
  AuthenticatedDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardPaymentsIndexRoute =
  AuthenticatedDashboardPaymentsIndexRouteImport.update({
    id: '/dashboard/payments/',
    path: '/dashboard/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardNotificationsIndexRoute =
  AuthenticatedDashboardNotificationsIndexRouteImport.update({
    id: '/dashboard/notifications/',
    path: '/dashboard/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEventsIndexRoute =
  AuthenticatedDashboardEventsIndexRouteImport.update({
    id: '/dashboard/events/',
    path: '/dashboard/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardDonationsIndexRoute =
  AuthenticatedDashboardDonationsIndexRouteImport.update({
    id: '/dashboard/donations/',
    path: '/dashboard/donations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardContentIndexRoute =
  AuthenticatedDashboardContentIndexRouteImport.update({
    id: '/dashboard/content/',
    path: '/dashboard/content/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardChurchesIndexRoute =
  AuthenticatedDashboardChurchesIndexRouteImport.update({
    id: '/dashboard/churches/',
    path: '/dashboard/churches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCategoriesIndexRoute =
  AuthenticatedDashboardCategoriesIndexRouteImport.update({
    id: '/dashboard/categories/',
    path: '/dashboard/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCampaignsIndexRoute =
  AuthenticatedDashboardCampaignsIndexRouteImport.update({
    id: '/dashboard/campaigns/',
    path: '/dashboard/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBibleIndexRoute =
  AuthenticatedDashboardBibleIndexRouteImport.update({
    id: '/dashboard/bible/',
    path: '/dashboard/bible/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardUsersUserIdIndexRoute =
  AuthenticatedDashboardUsersUserIdIndexRouteImport.update({
    id: '/dashboard/users/$userId/',
    path: '/dashboard/users/$userId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEventsEventIdIndexRoute =
  AuthenticatedDashboardEventsEventIdIndexRouteImport.update({
    id: '/dashboard/events/$eventId/',
    path: '/dashboard/events/$eventId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardContentNewIndexRoute =
  AuthenticatedDashboardContentNewIndexRouteImport.update({
    id: '/dashboard/content/new/',
    path: '/dashboard/content/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardContentContentIdIndexRoute =
  AuthenticatedDashboardContentContentIdIndexRouteImport.update({
    id: '/dashboard/content/$contentId/',
    path: '/dashboard/content/$contentId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardChurchesNewIndexRoute =
  AuthenticatedDashboardChurchesNewIndexRouteImport.update({
    id: '/dashboard/churches/new/',
    path: '/dashboard/churches/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardChurchesChurchIdIndexRoute =
  AuthenticatedDashboardChurchesChurchIdIndexRouteImport.update({
    id: '/dashboard/churches/$churchId/',
    path: '/dashboard/churches/$churchId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBibleBookIdIndexRoute =
  AuthenticatedDashboardBibleBookIdIndexRouteImport.update({
    id: '/dashboard/bible/$bookId/',
    path: '/dashboard/bible/$bookId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBibleBookIdChapterIdIndexRoute =
  AuthenticatedDashboardBibleBookIdChapterIdIndexRouteImport.update({
    id: '/dashboard/bible/$bookId/$chapterId/',
    path: '/dashboard/bible/$bookId/$chapterId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/bible/': typeof AuthenticatedDashboardBibleIndexRoute
  '/dashboard/campaigns/': typeof AuthenticatedDashboardCampaignsIndexRoute
  '/dashboard/categories/': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/dashboard/churches/': typeof AuthenticatedDashboardChurchesIndexRoute
  '/dashboard/content/': typeof AuthenticatedDashboardContentIndexRoute
  '/dashboard/donations/': typeof AuthenticatedDashboardDonationsIndexRoute
  '/dashboard/events/': typeof AuthenticatedDashboardEventsIndexRoute
  '/dashboard/notifications/': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/dashboard/payments/': typeof AuthenticatedDashboardPaymentsIndexRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
  '/dashboard/bible/$bookId/': typeof AuthenticatedDashboardBibleBookIdIndexRoute
  '/dashboard/churches/$churchId/': typeof AuthenticatedDashboardChurchesChurchIdIndexRoute
  '/dashboard/churches/new/': typeof AuthenticatedDashboardChurchesNewIndexRoute
  '/dashboard/content/$contentId/': typeof AuthenticatedDashboardContentContentIdIndexRoute
  '/dashboard/content/new/': typeof AuthenticatedDashboardContentNewIndexRoute
  '/dashboard/events/$eventId/': typeof AuthenticatedDashboardEventsEventIdIndexRoute
  '/dashboard/users/$userId/': typeof AuthenticatedDashboardUsersUserIdIndexRoute
  '/dashboard/bible/$bookId/$chapterId/': typeof AuthenticatedDashboardBibleBookIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/bible': typeof AuthenticatedDashboardBibleIndexRoute
  '/dashboard/campaigns': typeof AuthenticatedDashboardCampaignsIndexRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/dashboard/churches': typeof AuthenticatedDashboardChurchesIndexRoute
  '/dashboard/content': typeof AuthenticatedDashboardContentIndexRoute
  '/dashboard/donations': typeof AuthenticatedDashboardDonationsIndexRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsIndexRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
  '/dashboard/bible/$bookId': typeof AuthenticatedDashboardBibleBookIdIndexRoute
  '/dashboard/churches/$churchId': typeof AuthenticatedDashboardChurchesChurchIdIndexRoute
  '/dashboard/churches/new': typeof AuthenticatedDashboardChurchesNewIndexRoute
  '/dashboard/content/$contentId': typeof AuthenticatedDashboardContentContentIdIndexRoute
  '/dashboard/content/new': typeof AuthenticatedDashboardContentNewIndexRoute
  '/dashboard/events/$eventId': typeof AuthenticatedDashboardEventsEventIdIndexRoute
  '/dashboard/users/$userId': typeof AuthenticatedDashboardUsersUserIdIndexRoute
  '/dashboard/bible/$bookId/$chapterId': typeof AuthenticatedDashboardBibleBookIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/bible/': typeof AuthenticatedDashboardBibleIndexRoute
  '/_authenticated/dashboard/campaigns/': typeof AuthenticatedDashboardCampaignsIndexRoute
  '/_authenticated/dashboard/categories/': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/_authenticated/dashboard/churches/': typeof AuthenticatedDashboardChurchesIndexRoute
  '/_authenticated/dashboard/content/': typeof AuthenticatedDashboardContentIndexRoute
  '/_authenticated/dashboard/donations/': typeof AuthenticatedDashboardDonationsIndexRoute
  '/_authenticated/dashboard/events/': typeof AuthenticatedDashboardEventsIndexRoute
  '/_authenticated/dashboard/notifications/': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/_authenticated/dashboard/payments/': typeof AuthenticatedDashboardPaymentsIndexRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/_authenticated/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
  '/_authenticated/dashboard/bible/$bookId/': typeof AuthenticatedDashboardBibleBookIdIndexRoute
  '/_authenticated/dashboard/churches/$churchId/': typeof AuthenticatedDashboardChurchesChurchIdIndexRoute
  '/_authenticated/dashboard/churches/new/': typeof AuthenticatedDashboardChurchesNewIndexRoute
  '/_authenticated/dashboard/content/$contentId/': typeof AuthenticatedDashboardContentContentIdIndexRoute
  '/_authenticated/dashboard/content/new/': typeof AuthenticatedDashboardContentNewIndexRoute
  '/_authenticated/dashboard/events/$eventId/': typeof AuthenticatedDashboardEventsEventIdIndexRoute
  '/_authenticated/dashboard/users/$userId/': typeof AuthenticatedDashboardUsersUserIdIndexRoute
  '/_authenticated/dashboard/bible/$bookId/$chapterId/': typeof AuthenticatedDashboardBibleBookIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/'
    | '/dashboard/bible/'
    | '/dashboard/campaigns/'
    | '/dashboard/categories/'
    | '/dashboard/churches/'
    | '/dashboard/content/'
    | '/dashboard/donations/'
    | '/dashboard/events/'
    | '/dashboard/notifications/'
    | '/dashboard/payments/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
    | '/dashboard/bible/$bookId/'
    | '/dashboard/churches/$churchId/'
    | '/dashboard/churches/new/'
    | '/dashboard/content/$contentId/'
    | '/dashboard/content/new/'
    | '/dashboard/events/$eventId/'
    | '/dashboard/users/$userId/'
    | '/dashboard/bible/$bookId/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/bible'
    | '/dashboard/campaigns'
    | '/dashboard/categories'
    | '/dashboard/churches'
    | '/dashboard/content'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/bible/$bookId'
    | '/dashboard/churches/$churchId'
    | '/dashboard/churches/new'
    | '/dashboard/content/$contentId'
    | '/dashboard/content/new'
    | '/dashboard/events/$eventId'
    | '/dashboard/users/$userId'
    | '/dashboard/bible/$bookId/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/bible/'
    | '/_authenticated/dashboard/campaigns/'
    | '/_authenticated/dashboard/categories/'
    | '/_authenticated/dashboard/churches/'
    | '/_authenticated/dashboard/content/'
    | '/_authenticated/dashboard/donations/'
    | '/_authenticated/dashboard/events/'
    | '/_authenticated/dashboard/notifications/'
    | '/_authenticated/dashboard/payments/'
    | '/_authenticated/dashboard/settings/'
    | '/_authenticated/dashboard/users/'
    | '/_authenticated/dashboard/bible/$bookId/'
    | '/_authenticated/dashboard/churches/$churchId/'
    | '/_authenticated/dashboard/churches/new/'
    | '/_authenticated/dashboard/content/$contentId/'
    | '/_authenticated/dashboard/content/new/'
    | '/_authenticated/dashboard/events/$eventId/'
    | '/_authenticated/dashboard/users/$userId/'
    | '/_authenticated/dashboard/bible/$bookId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/users/': {
      id: '/_authenticated/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/payments/': {
      id: '/_authenticated/dashboard/payments/'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments/'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/notifications/': {
      id: '/_authenticated/dashboard/notifications/'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/events/': {
      id: '/_authenticated/dashboard/events/'
      path: '/dashboard/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof AuthenticatedDashboardEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/donations/': {
      id: '/_authenticated/dashboard/donations/'
      path: '/dashboard/donations'
      fullPath: '/dashboard/donations/'
      preLoaderRoute: typeof AuthenticatedDashboardDonationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/content/': {
      id: '/_authenticated/dashboard/content/'
      path: '/dashboard/content'
      fullPath: '/dashboard/content/'
      preLoaderRoute: typeof AuthenticatedDashboardContentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/churches/': {
      id: '/_authenticated/dashboard/churches/'
      path: '/dashboard/churches'
      fullPath: '/dashboard/churches/'
      preLoaderRoute: typeof AuthenticatedDashboardChurchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/categories/': {
      id: '/_authenticated/dashboard/categories/'
      path: '/dashboard/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/campaigns/': {
      id: '/_authenticated/dashboard/campaigns/'
      path: '/dashboard/campaigns'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/bible/': {
      id: '/_authenticated/dashboard/bible/'
      path: '/dashboard/bible'
      fullPath: '/dashboard/bible/'
      preLoaderRoute: typeof AuthenticatedDashboardBibleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/users/$userId/': {
      id: '/_authenticated/dashboard/users/$userId/'
      path: '/dashboard/users/$userId'
      fullPath: '/dashboard/users/$userId/'
      preLoaderRoute: typeof AuthenticatedDashboardUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/events/$eventId/': {
      id: '/_authenticated/dashboard/events/$eventId/'
      path: '/dashboard/events/$eventId'
      fullPath: '/dashboard/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedDashboardEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/content/new/': {
      id: '/_authenticated/dashboard/content/new/'
      path: '/dashboard/content/new'
      fullPath: '/dashboard/content/new/'
      preLoaderRoute: typeof AuthenticatedDashboardContentNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/content/$contentId/': {
      id: '/_authenticated/dashboard/content/$contentId/'
      path: '/dashboard/content/$contentId'
      fullPath: '/dashboard/content/$contentId/'
      preLoaderRoute: typeof AuthenticatedDashboardContentContentIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/churches/new/': {
      id: '/_authenticated/dashboard/churches/new/'
      path: '/dashboard/churches/new'
      fullPath: '/dashboard/churches/new/'
      preLoaderRoute: typeof AuthenticatedDashboardChurchesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/churches/$churchId/': {
      id: '/_authenticated/dashboard/churches/$churchId/'
      path: '/dashboard/churches/$churchId'
      fullPath: '/dashboard/churches/$churchId/'
      preLoaderRoute: typeof AuthenticatedDashboardChurchesChurchIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/bible/$bookId/': {
      id: '/_authenticated/dashboard/bible/$bookId/'
      path: '/dashboard/bible/$bookId'
      fullPath: '/dashboard/bible/$bookId/'
      preLoaderRoute: typeof AuthenticatedDashboardBibleBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/bible/$bookId/$chapterId/': {
      id: '/_authenticated/dashboard/bible/$bookId/$chapterId/'
      path: '/dashboard/bible/$bookId/$chapterId'
      fullPath: '/dashboard/bible/$bookId/$chapterId/'
      preLoaderRoute: typeof AuthenticatedDashboardBibleBookIdChapterIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardBibleIndexRoute: typeof AuthenticatedDashboardBibleIndexRoute
  AuthenticatedDashboardCampaignsIndexRoute: typeof AuthenticatedDashboardCampaignsIndexRoute
  AuthenticatedDashboardCategoriesIndexRoute: typeof AuthenticatedDashboardCategoriesIndexRoute
  AuthenticatedDashboardChurchesIndexRoute: typeof AuthenticatedDashboardChurchesIndexRoute
  AuthenticatedDashboardContentIndexRoute: typeof AuthenticatedDashboardContentIndexRoute
  AuthenticatedDashboardDonationsIndexRoute: typeof AuthenticatedDashboardDonationsIndexRoute
  AuthenticatedDashboardEventsIndexRoute: typeof AuthenticatedDashboardEventsIndexRoute
  AuthenticatedDashboardNotificationsIndexRoute: typeof AuthenticatedDashboardNotificationsIndexRoute
  AuthenticatedDashboardPaymentsIndexRoute: typeof AuthenticatedDashboardPaymentsIndexRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
  AuthenticatedDashboardUsersIndexRoute: typeof AuthenticatedDashboardUsersIndexRoute
  AuthenticatedDashboardBibleBookIdIndexRoute: typeof AuthenticatedDashboardBibleBookIdIndexRoute
  AuthenticatedDashboardChurchesChurchIdIndexRoute: typeof AuthenticatedDashboardChurchesChurchIdIndexRoute
  AuthenticatedDashboardChurchesNewIndexRoute: typeof AuthenticatedDashboardChurchesNewIndexRoute
  AuthenticatedDashboardContentContentIdIndexRoute: typeof AuthenticatedDashboardContentContentIdIndexRoute
  AuthenticatedDashboardContentNewIndexRoute: typeof AuthenticatedDashboardContentNewIndexRoute
  AuthenticatedDashboardEventsEventIdIndexRoute: typeof AuthenticatedDashboardEventsEventIdIndexRoute
  AuthenticatedDashboardUsersUserIdIndexRoute: typeof AuthenticatedDashboardUsersUserIdIndexRoute
  AuthenticatedDashboardBibleBookIdChapterIdIndexRoute: typeof AuthenticatedDashboardBibleBookIdChapterIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardBibleIndexRoute: AuthenticatedDashboardBibleIndexRoute,
  AuthenticatedDashboardCampaignsIndexRoute:
    AuthenticatedDashboardCampaignsIndexRoute,
  AuthenticatedDashboardCategoriesIndexRoute:
    AuthenticatedDashboardCategoriesIndexRoute,
  AuthenticatedDashboardChurchesIndexRoute:
    AuthenticatedDashboardChurchesIndexRoute,
  AuthenticatedDashboardContentIndexRoute:
    AuthenticatedDashboardContentIndexRoute,
  AuthenticatedDashboardDonationsIndexRoute:
    AuthenticatedDashboardDonationsIndexRoute,
  AuthenticatedDashboardEventsIndexRoute:
    AuthenticatedDashboardEventsIndexRoute,
  AuthenticatedDashboardNotificationsIndexRoute:
    AuthenticatedDashboardNotificationsIndexRoute,
  AuthenticatedDashboardPaymentsIndexRoute:
    AuthenticatedDashboardPaymentsIndexRoute,
  AuthenticatedDashboardSettingsIndexRoute:
    AuthenticatedDashboardSettingsIndexRoute,
  AuthenticatedDashboardUsersIndexRoute: AuthenticatedDashboardUsersIndexRoute,
  AuthenticatedDashboardBibleBookIdIndexRoute:
    AuthenticatedDashboardBibleBookIdIndexRoute,
  AuthenticatedDashboardChurchesChurchIdIndexRoute:
    AuthenticatedDashboardChurchesChurchIdIndexRoute,
  AuthenticatedDashboardChurchesNewIndexRoute:
    AuthenticatedDashboardChurchesNewIndexRoute,
  AuthenticatedDashboardContentContentIdIndexRoute:
    AuthenticatedDashboardContentContentIdIndexRoute,
  AuthenticatedDashboardContentNewIndexRoute:
    AuthenticatedDashboardContentNewIndexRoute,
  AuthenticatedDashboardEventsEventIdIndexRoute:
    AuthenticatedDashboardEventsEventIdIndexRoute,
  AuthenticatedDashboardUsersUserIdIndexRoute:
    AuthenticatedDashboardUsersUserIdIndexRoute,
  AuthenticatedDashboardBibleBookIdChapterIdIndexRoute:
    AuthenticatedDashboardBibleBookIdChapterIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
