-- ============================================================================
-- RBAC via Custom Access Token Hook  (TEST / fully additive — nothing dropped)
-- ============================================================================
-- Goal: put the user's roles + permissions on the JWT so the client can read
-- them with `supabase.auth.getClaims()` instead of querying `user_roles` on
-- every check.
--
-- This migration is intentionally NON-destructive:
--   * It does NOT touch the existing `user_role` enum or the `user_roles` table.
--   * It bridges the existing roles to the new `app_role` set the app wants.
--
-- What it adds:
--   * app_role / app_permission enums  (the new role taxonomy)
--   * role_permissions table (role -> permission), seeded from sensible defaults
--   * map_user_role_to_app_role(): bridges existing user_role -> app_role
--   * custom_access_token_hook(): injects `user_roles` + `permissions` claims
--   * authorize(): RLS helper that reads the JWT `permissions` claim
--   * rbac_test table: throwaway table to verify RLS without touching real data
--
-- After running this SQL:
--   1) Dashboard > Authentication > Hooks > Custom Access Token
--        -> pg-functions://postgres/public.custom_access_token_hook   (enable)
--   2) Sign out / back in (or refresh the session) so a fresh token is minted.
--   3) `supabase gen types ...` to refresh database.types.ts.
--
-- Everything here is reversible via `rbac_custom_claims_revert.sql`.
-- ============================================================================

-- 1. Enums -------------------------------------------------------------------
do $$ begin
    create type public.app_role as enum (
        'super_admin',   -- System-wide
        'admin',         -- Resource-wide
        'manager',       -- Team / church management (was church_admin)
        'editor',        -- Content lifecycle (was content_admin)
        'contributor',   -- Limited creation (was content_creator)
        'viewer'         -- Read only (was user)
    );
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.app_permission as enum (
        'content.create',
        'content.update',
        'content.delete',
        'content.approve',
        'church.manage',
        'users.manage',
        'donations.manage',
        'events.manage'
    );
exception when duplicate_object then null; end $$;

-- 2. role -> permission catalogue -------------------------------------------
create table if not exists public.role_permissions (
    id          bigint generated by default as identity primary key,
    role        public.app_role not null,
    permission  public.app_permission not null,
    unique (role, permission)
);
comment on table public.role_permissions is
    'RBAC: permissions granted to each app_role. Read by custom_access_token_hook.';

-- Seed (idempotent). Mirrors the existing role hierarchy.
insert into public.role_permissions (role, permission) values
    -- super_admin: everything
    ('super_admin', 'content.create'),
    ('super_admin', 'content.update'),
    ('super_admin', 'content.delete'),
    ('super_admin', 'content.approve'),
    ('super_admin', 'church.manage'),
    ('super_admin', 'users.manage'),
    ('super_admin', 'donations.manage'),
    ('super_admin', 'events.manage'),
    -- admin: everything
    ('admin', 'content.create'),
    ('admin', 'content.update'),
    ('admin', 'content.delete'),
    ('admin', 'content.approve'),
    ('admin', 'church.manage'),
    ('admin', 'users.manage'),
    ('admin', 'donations.manage'),
    ('admin', 'events.manage'),
    -- manager (was church_admin): runs a church + its people/content/events/donations
    ('manager', 'content.create'),
    ('manager', 'content.update'),
    ('manager', 'content.delete'),
    ('manager', 'content.approve'),
    ('manager', 'church.manage'),
    ('manager', 'users.manage'),
    ('manager', 'donations.manage'),
    ('manager', 'events.manage'),
    -- editor (was content_admin): full content lifecycle + events
    ('editor', 'content.create'),
    ('editor', 'content.update'),
    ('editor', 'content.delete'),
    ('editor', 'content.approve'),
    ('editor', 'events.manage'),
    -- contributor (was content_creator): create / update content only
    ('contributor', 'content.create'),
    ('contributor', 'content.update')
    -- viewer (was user): read only, no write permissions
on conflict (role, permission) do nothing;

-- 3. Bridge: existing user_role enum -> new app_role -------------------------
create or replace function public.map_user_role_to_app_role(p_role public.user_role)
returns public.app_role
language sql
immutable
set search_path = ''
as $$
    select case p_role
        when 'super_admin'     then 'super_admin'::public.app_role
        when 'admin'           then 'admin'::public.app_role
        when 'church_admin'    then 'manager'::public.app_role
        when 'content_admin'   then 'editor'::public.app_role
        when 'content_creator' then 'contributor'::public.app_role
        else 'viewer'::public.app_role
    end;
$$;

-- 4. Custom Access Token Hook ------------------------------------------------
-- Injects two claims:
--   user_roles  -> [{ "role": "manager", "churchId": "..." }, ...]
--   permissions -> ["content.create", "content.approve", ...]  (de-duplicated)
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
    claims    jsonb;
    uid       uuid;
    roles_arr jsonb;
    perms_arr jsonb;
begin
    uid := (event->>'user_id')::uuid;
    claims := coalesce(event->'claims', '{}'::jsonb);

    -- Per-church roles, mapped onto the new app_role taxonomy.
    select coalesce(
               jsonb_agg(jsonb_build_object(
                   'role', public.map_user_role_to_app_role(ur.role),
                   'churchId', ur.church_id
               )),
               '[]'::jsonb
           )
      into roles_arr
      from public.user_roles ur
     where ur.user_id = uid;

    -- Flat, de-duplicated permission set across all of the user's roles.
    select coalesce(jsonb_agg(distinct rp.permission), '[]'::jsonb)
      into perms_arr
      from public.user_roles ur
      join public.role_permissions rp
        on rp.role = public.map_user_role_to_app_role(ur.role)
     where ur.user_id = uid;

    claims := jsonb_set(claims, '{user_roles}', roles_arr);
    claims := jsonb_set(claims, '{permissions}', perms_arr);

    event := jsonb_set(event, '{claims}', claims);
    return event;
exception
    when others then
        -- Never block token issuance while testing; just return it untouched.
        return event;
end;
$$;

comment on function public.custom_access_token_hook is
    'RBAC: injects user_roles + permissions claims. Enable in Dashboard > Authentication > Hooks > Custom Access Token.';

-- 5. Grants / RLS so the auth admin can run the hook & read the tables -------
grant usage on schema public to supabase_auth_admin;

grant execute on function public.custom_access_token_hook(jsonb) to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook(jsonb) from authenticated, anon, public;

grant execute on function public.map_user_role_to_app_role(public.user_role) to supabase_auth_admin;

grant select on public.user_roles to supabase_auth_admin;
grant select on public.role_permissions to supabase_auth_admin;

alter table public.role_permissions enable row level security;

drop policy if exists "auth admin can read role_permissions" on public.role_permissions;
create policy "auth admin can read role_permissions"
    on public.role_permissions
    as permissive for select
    to supabase_auth_admin
    using (true);

-- Additive: lets the hook read user_roles. Existing policies are untouched.
drop policy if exists "auth admin can read user_roles" on public.user_roles;
create policy "auth admin can read user_roles"
    on public.user_roles
    as permissive for select
    to supabase_auth_admin
    using (true);

-- Authenticated users may read the permission catalogue (handy for app UI).
drop policy if exists "authenticated can read role_permissions" on public.role_permissions;
create policy "authenticated can read role_permissions"
    on public.role_permissions
    as permissive for select
    to authenticated
    using (true);

-- 6. authorize() helper for RLS ---------------------------------------------
-- Reads the JWT `permissions` claim minted by the hook above. The `?` operator
-- returns true when the requested permission exists in the claim's JSON array.
create or replace function public.authorize(requested_permission public.app_permission)
returns boolean
language sql
stable
set search_path = ''
as $$
    select coalesce(
        (auth.jwt() -> 'permissions') ? requested_permission::text,
        false
    );
$$;

comment on function public.authorize is
    'RBAC: true when the caller''s JWT permissions claim contains the requested permission.';

grant execute on function public.authorize(public.app_permission) to authenticated, anon;

-- 7. Throwaway table to verify RLS end-to-end (safe to drop) -----------------
-- A viewer (no content.create) cannot SELECT/INSERT here; editor/admin can.
create table if not exists public.rbac_test (
    id          uuid primary key default gen_random_uuid(),
    label       text,
    created_by  uuid default auth.uid(),
    created_at  timestamptz not null default now()
);
alter table public.rbac_test enable row level security;

drop policy if exists "rbac_test select" on public.rbac_test;
create policy "rbac_test select"
    on public.rbac_test for select to authenticated
    using (public.authorize('content.create'));

drop policy if exists "rbac_test insert" on public.rbac_test;
create policy "rbac_test insert"
    on public.rbac_test for insert to authenticated
    with check (public.authorize('content.create'));

drop policy if exists "rbac_test delete" on public.rbac_test;
create policy "rbac_test delete"
    on public.rbac_test for delete to authenticated
    using (public.authorize('content.delete'));
